language: rust
cache: cargo

rust:
  - 1.37.0
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: stable
      env: RUN=FMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check

matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo test $FEATURES