
name: osci-cli
base: core18
version: '0.1.1'
summary: Tool to query OSCI
description: |
  osci-cli is a tool to query UOSCI (Ubuntu OpenStack CI)
license: MIT
grade: stable
confinement: strict

parts:
  osci-cli:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev
apps:
  osci-cli:
    adapter: none
    command: ./bin/osci-cli
    plugs:
      - network